//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPattern.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignPattern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount that wants to be removed is biggest than the amount already added. In this case, {0} items will be removed and this product will be removed from the list.
        /// </summary>
        internal static string AmountExceedsAddedItems {
            get {
                return ResourceManager.GetString("AmountExceedsAddedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you finished the purchase ? (Y) Yes / (N) No.
        /// </summary>
        internal static string FinishedPurchase {
            get {
                return ResourceManager.GetString("FinishedPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidProductName.
        /// </summary>
        internal static string InvalidProductName {
            get {
                return ResourceManager.GetString("InvalidProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Quantity.
        /// </summary>
        internal static string InvalidProductQuantity {
            get {
                return ResourceManager.GetString("InvalidProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the product you want to buy; \n{0}.
        /// </summary>
        internal static string ProductEnterMessage {
            get {
                return ResourceManager.GetString("ProductEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Not Found.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exception is thrown when a user attempts to enter or search for a product that has not been registered in the system. It ensures that operations requiring an existing product do not proceed with invalid or missing data..
        /// </summary>
        internal static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove an item ? (Y) Yes / (N) No.
        /// </summary>
        internal static string RemoveAnItem {
            get {
                return ResourceManager.GetString("RemoveAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove another item ? (Y) Yes / (N) No.
        /// </summary>
        internal static string RemoveAnotherItem {
            get {
                return ResourceManager.GetString("RemoveAnotherItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the product name to be removed:.
        /// </summary>
        internal static string RemoveProduct {
            get {
                return ResourceManager.GetString("RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much items ({0}) do you want to remove ?.
        /// </summary>
        internal static string RemoveQuantityItems {
            get {
                return ResourceManager.GetString("RemoveQuantityItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price: U${0}.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
    }
}
